export const POST_TEXT =  'POST_TEXT';
export const POST_TEXT_FAIL =  'POST_TEXT_FAIL';
export const POST_TEXT_SUCCESS =  'POST_TEXT_SUCCESS';

export const FETCH_RESPONSE =  'FETCH_RESPONSE';
export const FETCH_RESPONSE_SUCCESS =  'FETCH_RESPONSE_SUCCESS';
export const FETCH_RESPONSE_FAIL =  'FETCH_RESPONSE_FAIL';

export const IS_LOADING =  'IS_LOADING';
export const FINISHED_LOADING =  'FINISHED_LOADING';
